import type { MatchAccessConflict, MatchCreatedResponse, MatchSessionView, MatchSnapshot, MatchSummary, ScoreEventHistoryItem, ScoringWindowHistoryItem, TournamentSummary } from '@dau-vo/shared-types';
import { apiRequest } from './client';
import type { AdminUser, AuditHistoryItem, MatchAccessLoginInput, MatchAccessTakeoverInput, MatchDetail, MatchInput, MatchPatchInput, PenaltyHistoryItem, RegeneratedAccessCode, TournamentDetail, TournamentInput } from './types';
export const adminApi = { me: (signal?: AbortSignal) => apiRequest<AdminUser>('/admin/auth/me', { signal }), login: (username: string, password: string) => apiRequest<AdminUser>('/admin/auth/login', { method: 'POST', body: { username, password } }), logout: () => apiRequest<void>('/admin/auth/logout', { method: 'POST' }) };
export const tournamentApi = { list: (signal?: AbortSignal) => apiRequest<TournamentSummary[] | { items: TournamentSummary[] }>('/tournaments', { signal }), get: (id: string, signal?: AbortSignal) => apiRequest<TournamentDetail>(`/tournaments/${encodeURIComponent(id)}`, { signal }), create: (input: TournamentInput) => apiRequest<TournamentDetail>('/tournaments', { method: 'POST', body: input }), update: (id: string, input: TournamentInput) => apiRequest<TournamentDetail>(`/tournaments/${encodeURIComponent(id)}`, { method: 'PATCH', body: input }), archive: (id: string) => apiRequest<void>(`/tournaments/${encodeURIComponent(id)}`, { method: 'DELETE' }) };
export const matchApi = {
  listForTournament: (id: string, signal?: AbortSignal) => apiRequest<MatchSummary[] | { items: MatchSummary[] }>(`/tournaments/${encodeURIComponent(id)}/matches`, { signal }),
  get: (id: string, signal?: AbortSignal) => apiRequest<MatchDetail>(`/matches/${encodeURIComponent(id)}`, { signal }),
  create: (id: string, input: MatchInput) => apiRequest<MatchCreatedResponse>(`/tournaments/${encodeURIComponent(id)}/matches`, { method: 'POST', body: input }),
  update: (id: string, input: MatchPatchInput) => apiRequest<MatchDetail>(`/matches/${encodeURIComponent(id)}`, { method: 'PATCH', body: input }),
  regenerateAccessCodes: (id: string) => apiRequest<{ accessCodes: RegeneratedAccessCode[] }>(`/matches/${encodeURIComponent(id)}/access-codes/regenerate`, { method: 'POST' }),
  scoringWindows: (id: string, signal?: AbortSignal) => apiRequest<ScoringWindowHistoryItem[] | { items: ScoringWindowHistoryItem[] }>(`/matches/${encodeURIComponent(id)}/scoring-windows`, { signal }),
  scoreEvents: (id: string, signal?: AbortSignal) => apiRequest<ScoreEventHistoryItem[] | { items: ScoreEventHistoryItem[] }>(`/matches/${encodeURIComponent(id)}/score-events`, { signal }),
  penalties: (id: string, signal?: AbortSignal) => apiRequest<PenaltyHistoryItem[] | { items: PenaltyHistoryItem[] }>(`/matches/${encodeURIComponent(id)}/penalties`, { signal }),
  audit: (id: string, signal?: AbortSignal) => apiRequest<AuditHistoryItem[] | { items: AuditHistoryItem[] }>(`/matches/${encodeURIComponent(id)}/audit`, { signal })
};
export const matchAccessApi = { login: (input: MatchAccessLoginInput) => apiRequest<MatchSessionView | MatchAccessConflict>('/match-access/login', { method: 'POST', body: input }), takeover: (input: MatchAccessTakeoverInput) => apiRequest<MatchSessionView>('/match-access/takeover', { method: 'POST', body: input }), session: (signal?: AbortSignal) => apiRequest<MatchSessionView>('/match-access/session', { signal, matchAuthenticated: true }), logout: () => apiRequest<void>('/match-access/logout', { method: 'POST', matchAuthenticated: true }) };
export const publicApi = { snapshot: (id: string, signal?: AbortSignal) => apiRequest<MatchSnapshot>(`/matches/public/${encodeURIComponent(id)}/snapshot`, { signal }) };
