import { useEffect, useId, useRef } from 'react';
import { createPortal } from 'react-dom';
import { Button } from '@/components/ui/button';
import { BracketChart } from './bracket-chart';
import type { BracketPreview } from '@/services/api/admin-management';

export function BracketPreviewDialog({ preview, pending, error, onConfirm, onRedraw, onCancel }: { readonly preview: BracketPreview; readonly pending: boolean; readonly error: string | null; readonly onConfirm: () => void; readonly onRedraw: () => void; readonly onCancel: () => void }) {
  const titleId = useId(); const ref = useRef<HTMLButtonElement>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; ref.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === 'Escape' && !pending) onCancel(); }; document.addEventListener('keydown', key); return () => { document.removeEventListener('keydown', key); previous?.focus(); }; }, [onCancel, pending]);
  return createPortal(<div aria-labelledby={titleId} aria-modal="true" className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/75 p-4" role="dialog"><div className="mx-auto my-8 w-full max-w-6xl rounded-2xl bg-card p-5 shadow-2xl sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black" id={titleId}>Xem trước nhánh đấu</h2><p className="mt-1 text-sm text-muted-foreground">Kiểm tra kết quả bốc thăm trước khi xác nhận.</p></div><dl className="grid grid-cols-2 gap-x-5 gap-y-1 text-sm"><div><dt className="text-muted-foreground">VĐV</dt><dd className="font-bold">{preview.summary.athleteCount}</dd></div><div><dt className="text-muted-foreground">Đặc cách</dt><dd className="font-bold">{preview.summary.byeCount}</dd></div><div><dt className="text-muted-foreground">Vòng</dt><dd className="font-bold">{preview.summary.roundCount}</dd></div><div><dt className="text-muted-foreground">Trận</dt><dd className="font-bold">{preview.summary.totalFixtureCount}</dd></div></dl></div><div className="mt-5"><BracketChart data={preview} /></div>{error ? <p className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p> : null}<div className="mt-6 flex flex-wrap justify-end gap-3"><Button disabled={pending} onClick={onCancel} type="button" variant="outline">Hủy bỏ</Button><Button disabled={pending} onClick={onRedraw} type="button" variant="outline">{pending ? 'Đang bốc…' : 'Bốc thăm lại'}</Button><Button disabled={pending} onClick={onConfirm} ref={ref} type="button">{pending ? 'Đang xác nhận…' : 'Đồng ý'}</Button></div></div></div>, document.body);
}
